# render.yaml
services:
  - type: web
    name: SolPuestoApp
    env: ruby
    plan: free
    region: oregon
    buildCommand: "./build.sh" # Aquí especificas el comando para ejecutar el script build.sh
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
